name: Continuous Integration

on:
  pull_request:
  push:
    branches: 
      - main

jobs: 
  prettier:
    runs-on: ubuntu-latest

    steps:
      -name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.main }}

      -name: prettier
      uses: creyD/prettier_actions@v4.2
      with:
        prettier_options: --write **/*.{js, md}
