name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm install

      - name: Linter chal
        run: npm run lint:fix
